USE [master]
GO

/****** Object:  Database [MVCWebLab]    Script Date: 2021-04-22 ¿ÀÈÄ 3:10:28 ******/
CREATE DATABASE [MVCWebLab]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MVCWebLab', FILENAME = N'D:\Datas\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MVCWebLab.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MVCWebLab_log', FILENAME = N'D:\Datas\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MVCWebLab_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MVCWebLab].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MVCWebLab] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [MVCWebLab] SET ANSI_NULLS ON 
GO

ALTER DATABASE [MVCWebLab] SET ANSI_PADDING ON 
GO

ALTER DATABASE [MVCWebLab] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [MVCWebLab] SET ARITHABORT ON 
GO

ALTER DATABASE [MVCWebLab] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MVCWebLab] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MVCWebLab] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MVCWebLab] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MVCWebLab] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [MVCWebLab] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [MVCWebLab] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MVCWebLab] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [MVCWebLab] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MVCWebLab] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MVCWebLab] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MVCWebLab] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MVCWebLab] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MVCWebLab] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MVCWebLab] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MVCWebLab] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MVCWebLab] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MVCWebLab] SET RECOVERY FULL 
GO

ALTER DATABASE [MVCWebLab] SET  MULTI_USER 
GO

ALTER DATABASE [MVCWebLab] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [MVCWebLab] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MVCWebLab] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MVCWebLab] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MVCWebLab] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MVCWebLab] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MVCWebLab] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MVCWebLab] SET  READ_WRITE 
GO


